{
 "title": "Air Quality All Sensors",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality_batch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"co2_value\")\n  |> filter(fn: (r) => r[\"topic\"] == \"Snow/up/582D3470CEBA\")\n"
    }
   ]
  },
  {
   "title": "eTVOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality_batch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tvoc_index_value\")\n  |> filter(fn: (r) => r[\"topic\"] == \"Snow/up/582D3470CEBA\")\n"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality_batch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm25_value\")\n  |> filter(fn: (r) => r[\"topic\"] == \"Snow/up/582D3470CEBA\")\n"
    }
   ]
  },
  {
   "title": "PM10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality_batch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pm10_value\")\n  |> filter(fn: (r) => r[\"topic\"] == \"Snow/up/582D3470CEBA\")\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality_batch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature_value\")\n  |> filter(fn: (r) => r[\"topic\"] == \"Snow/up/582D3470CEBA\")\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality_batch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity_value\")\n  |> filter(fn: (r) => r[\"topic\"] == \"Snow/up/582D3470CEBA\")\n"
    }
   ]
  },
  {
   "title": "Noise",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"some_data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"air_quality_batch\")\n  |> filter(fn: (r) => r[\"_field\"] == \"noise_value\")\n  |> filter(fn: (r) => r[\"topic\"] == \"Snow/up/582D3470CEBA\")\n "
    }
   ]
  }
 ]
}